# Hybrid Docker Compose configuration for BlackCnote
# This file combines development and production features

services:
  # WordPress Application - Hybrid Configuration
  wordpress:
    image: wordpress:6.8-apache
    container_name: blackcnote_wordpress_hybrid
    ports:
      - "8888:80"
    environment:
      # WordPress configuration
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: blackcnote
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: blackcnote_password
      WORDPRESS_TABLE_PREFIX: wp_
      # WordPress URLs - Hybrid
      WP_HOME: http://localhost:8888
      WP_SITEURL: http://localhost:8888
      WP_CONTENT_URL: http://localhost:8888/wp-content
      # WordPress settings - Hybrid
      WP_DEBUG: true
      WP_DEBUG_DISPLAY: false
      WP_DEBUG_LOG: true
      SCRIPT_DEBUG: true
      SAVEQUERIES: true
      # Security - Hybrid
      FORCE_SSL_ADMIN: false
      FORCE_SSL_LOGIN: false
      # Performance - Hybrid
      WP_MEMORY_LIMIT: 384M
      WP_MAX_MEMORY_LIMIT: 768M
      # Updates - Hybrid
      AUTOMATIC_UPDATER_DISABLED: true
      WP_AUTO_UPDATE_CORE: false
      # EXCLUSIVE BLACKCNOTE WP-CONTENT PATH
      WP_CONTENT_DIR: /var/www/html/wp-content
    volumes:
      # EXCLUSIVELY mount blackcnote directory as WordPress root
      - ./blackcnote:/var/www/html:cached
      # Use blackcnote wp-config.php
      - ./blackcnote/wp-config.php:/var/www/html/wp-config.php
      - ./logs/wordpress:/var/www/html/logs
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - blackcnote_network

  # MySQL Database - Hybrid Configuration
  mysql:
    image: mysql:8.0
    container_name: blackcnote_mysql_hybrid
    environment:
      MYSQL_ROOT_PASSWORD: blackcnote_password
      MYSQL_DATABASE: blackcnote
      MYSQL_USER: blackcnote_user
      MYSQL_PASSWORD: blackcnote_password
      # Performance settings - Hybrid
      MYSQL_INNODB_BUFFER_POOL_SIZE: 384M
      MYSQL_INNODB_LOG_FILE_SIZE: 96M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 1
      MYSQL_MAX_CONNECTIONS: 100
      MYSQL_QUERY_CACHE_SIZE: 32M
      MYSQL_QUERY_CACHE_TYPE: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./backups:/var/lib/mysql-backups
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=384M
      --slow-query-log=1
      --long-query-time=5
      --log-error=/var/log/mysql/error.log
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
    restart: unless-stopped
    networks:
      - blackcnote_network

  # Redis Cache - Hybrid Configuration
  redis:
    image: redis:7-alpine
    container_name: blackcnote_redis_hybrid
    command: >
      redis-server
      --loglevel notice
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./logs/redis:/var/log/redis
    restart: unless-stopped
    networks:
      - blackcnote_network

  # phpMyAdmin for Database Management - Hybrid
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: blackcnote_phpmyadmin_hybrid
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: blackcnote_password
      MYSQL_ROOT_PASSWORD: blackcnote_password
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - blackcnote_network

  # React Development Server - Hybrid
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    container_name: blackcnote_react_hybrid
    ports:
      - "5174:5174"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    restart: unless-stopped
    networks:
      - blackcnote_network

  # BlackCnote Debug System - Hybrid
  blackcnote_debug:
    image: php:8.1-cli
    container_name: blackcnote_debug_hybrid
    volumes:
      # EXCLUSIVELY monitor blackcnote directory
      - ./blackcnote:/app/blackcnote
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    command: ["php", "bin/blackcnote-debug-daemon.php", "--hybrid"]
    restart: always
    networks:
      - blackcnote_network

  # BlackCnote Metrics Exporter - Hybrid
  blackcnote_debug_exporter:
    image: php:8.1-cli
    container_name: blackcnote_debug_exporter_hybrid
    volumes:
      # EXCLUSIVELY monitor blackcnote directory
      - ./blackcnote:/app/blackcnote
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    command: ["php", "bin/blackcnote-metrics-exporter.php", "--serve", "9091", "--hybrid"]
    ports:
      - "9091:9091"
    restart: always
    depends_on:
      - blackcnote_debug
    networks:
      - blackcnote_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  blackcnote_network:
    driver: bridge 