# Development-specific overrides for BlackCnote Docker Compose
# This file is automatically loaded by docker-compose

services:
  wordpress:
    environment:
      # Development-specific environment variables
      WP_DEBUG: true
      WP_DEBUG_DISPLAY: true
      WP_DEBUG_LOG: true
      SCRIPT_DEBUG: true
      SAVEQUERIES: true
      WP_CACHE: false
      # Development URLs - Fixed to match nginx configuration
      WP_HOME: http://localhost:8888
      WP_SITEURL: http://localhost:8888
      WP_CONTENT_URL: http://localhost:8888/wp-content
    volumes:
      # Additional development volumes
      - ./logs:/var/www/html/logs:delegated
      - ./scripts:/var/www/html/scripts:delegated
      - ./tools:/var/www/html/tools:delegated
      
      # Override WordPress core directories with local versions
      # Uncomment the lines below to use your local wp-includes, wp-admin, etc.
      - ../wp-includes:/var/www/html/wp-includes:delegated
      # - ../wp-admin:/var/www/html/wp-admin:delegated
      # - ../wp-content:/var/www/html/wp-content:delegated
      # - ../wp-content/plugins:/var/www/html/wp-content/plugins:delegated
      # - ../wp-content/themes:/var/www/html/wp-content/themes:delegated
      # - ../wp-content/uploads:/var/www/html/wp-content/uploads:delegated
      
      # Alternative: Override only specific files/directories
      # - ../wp-includes/version.php:/var/www/html/wp-includes/version.php:delegated
      # - ../wp-includes/functions.php:/var/www/html/wp-includes/functions.php:delegated
      # - ../wp-includes/class-wp.php:/var/www/html/wp-includes/class-wp.php:delegated

  mysql:
    environment:
      # Development MySQL settings
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M --slow-query-log=1 --long-query-time=2

  redis:
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel verbose

  # Development tools
  dev-tools:
    environment:
      NODE_ENV: development
      DEBUG: "*"
    volumes:
      - ./logs:/app/logs:delegated
      - ./scripts:/app/scripts:delegated
      - ./tools:/app/tools:delegated

  # File watcher for development
  file-watcher:
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 1000
    volumes:
      - ./logs:/app/logs:delegated 